eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}

# http:// This speciﬁes the protocol used for communication, in this case, HTTP.
# eureka-0: This is the hostname of the Eureka server instance within the Kubernetes cluster.
#           The "0" in the hostname suggests that it might be the ﬁrst instance of the Eureka server.
#           The speciﬁc naming convention may vary depending on the deployment conﬁguration.
# eureka-service: This is the name of the Kubernetes service associated with the Eureka server.
#                 Kubernetes services provide a stable endpoint for accessing pods within the cluster.
# default: This is the namespace in which the Eureka service and pods are deployed.
#          Kubernetes namespaces provide a way to isolate resources within a cluster.
# svc.cluster.local: This is the domain sufix for Kubernetes services within the cluster.
